
import com.mycompany.example.COMPANY;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author akdag
 */
public class CUSTOMER_PAGE extends javax.swing.JFrame {

    COMPANY şirket;
    CUSTOMER customer;

    String username1;

    DefaultTableModel model1;//jtable for showing expenses
    DefaultListModel model2;//jlist for showing revenues

    /**
     * Creates new form CUSTOMER_PAGE
     */
    public CUSTOMER_PAGE(String username) {// creating objects
        initComponents();
        şirket = new COMPANY();
        model1 = new DefaultTableModel();
        model2 = new DefaultListModel();
        customer = MANAGE.GetCustomerByUsername(username, şirket);//geting customer infos from database
        model1.setColumnIdentifiers(new Object[]{"USERNAME", "SALARİES", "RENT", "MARKETİNG", "TAXES", "SERVİCES", "TRANSPORTATİON", "TOTAL_DEBT"});// did this for showing all expenses
        TABLE.setModel(model1);
        LİST.setModel(model2);

        username1 = username;

        USERNAME.setText(username);
        NAME.setText(customer.name);// setting infos from databse to fields

        PASSWORD.setText(customer.password);

        SURNAME.setText(customer.surname);
        MAİL.setText(customer.mail);
        POSİTİON.setText(customer.position);
        İNVOİNCE.setText(customer.invoince);
        COMPANY_NAME.setText(şirket.company_name);
        TYPE.setText(şirket.type);
        String total = String.valueOf(şirket.total_money);
        String last = String.valueOf(şirket.last_revenue);
        String debt = String.valueOf(şirket.paid_debt);

        TOTAL.setText(total);
        LAST.setText(last);
        DEBT.setText(debt);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        COMPANY_NAME = new javax.swing.JTextField();
        TYPE = new javax.swing.JLabel();
        TOTAL = new javax.swing.JLabel();
        LAST = new javax.swing.JLabel();
        DEBT = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        enter_revenue = new javax.swing.JButton();
        new_revenue = new javax.swing.JTextField();
        UPDATE_COM = new javax.swing.JButton();
        SHOW = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TABLE = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        LİST = new javax.swing.JList<>();
        see_expense = new javax.swing.JButton();
        see_revenues = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        PASSWORD = new javax.swing.JTextField();
        NAME = new javax.swing.JTextField();
        SURNAME = new javax.swing.JTextField();
        MAİL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        İNVOİNCE = new javax.swing.JLabel();
        UPDATE = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        USERNAME = new javax.swing.JLabel();
        POSİTİON = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jTextField4.setText("jTextField4");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setText("jTextField5");

        jLabel1.setText("USERNAME");

        jLabel2.setText("NAME");

        jLabel3.setText("SURNAME");

        jLabel4.setText("MAIL");

        jLabel5.setText("PHONE NUMBER");

        jLabel6.setText("RESIDENCE");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(92, 92, 92))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jScrollPane1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(324, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(154, 154, 154))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel15.setText("Company name");

        jLabel16.setText("Type company");

        jLabel17.setText("Total Money");

        jLabel18.setText("Last Revenue");

        jLabel19.setText("The last paid debt");

        jLabel20.setText("jLabel20");

        COMPANY_NAME.setText("jTextField14");

        TYPE.setText("jLabel21");

        TOTAL.setText("jLabel22");

        LAST.setText("jLabel23");

        DEBT.setText("jLabel24");

        jLabel25.setText("jLabel25");

        enter_revenue.setText("ENTER NEW REVENUE");
        enter_revenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_revenueActionPerformed(evt);
            }
        });

        UPDATE_COM.setText("UPDATE");
        UPDATE_COM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATE_COMActionPerformed(evt);
            }
        });

        SHOW.setText("SHOW EXPENSES");
        SHOW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOWActionPerformed(evt);
            }
        });

        TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(TABLE);

        jScrollPane4.setViewportView(LİST);

        see_expense.setText("SEE EXPENSES");
        see_expense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                see_expenseActionPerformed(evt);
            }
        });

        see_revenues.setText("SEE REVENUES");
        see_revenues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                see_revenuesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(94, 94, 94)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(COMPANY_NAME, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(TYPE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TOTAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LAST, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DEBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SHOW, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(UPDATE_COM, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(enter_revenue, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(new_revenue)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(see_expense, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(see_revenues, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(new_revenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(COMPANY_NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(enter_revenue))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(TYPE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(TOTAL)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(see_expense)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(LAST))
                        .addGap(11, 11, 11)
                        .addComponent(UPDATE_COM)
                        .addGap(7, 7, 7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(DEBT))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel25)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(SHOW, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(see_revenues)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("COMPANY", jPanel3);

        PASSWORD.setText("jTextField7");

        NAME.setText("jTextField8");

        SURNAME.setText("jTextField9");

        MAİL.setText("jTextField10");

        jLabel7.setText("Username");

        jLabel8.setText("Password");

        jLabel9.setText("Name");

        jLabel10.setText("Surname");

        jLabel11.setText("Mail");

        jLabel12.setText("Position");

        jLabel13.setText("İnvoince");

        İNVOİNCE.setText("jLabel14");

        UPDATE.setText("Update");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });

        DELETE.setText("Delete");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });

        USERNAME.setText("jLabel21");

        POSİTİON.setText("jLabel14");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 76, 76)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PASSWORD)
                    .addComponent(NAME)
                    .addComponent(SURNAME)
                    .addComponent(MAİL, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                    .addComponent(USERNAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(İNVOİNCE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(POSİTİON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(117, 117, 117)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UPDATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DELETE, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addContainerGap(722, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(USERNAME))
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(UPDATE))))
                                    .addComponent(jLabel8))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(SURNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(DELETE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MAİL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(50, 50, 50))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(POSİTİON)))
                        .addGap(31, 31, 31)
                        .addComponent(İNVOİNCE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel13)))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PERSONEL", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
        // TODO add your handling code here:
        String username = USERNAME.getText();
        String text7 = USERNAME.getText();
        Pattern ptrn7 = Pattern.compile("^(.)+$", Pattern.CASE_INSENSITIVE);//at least one any caracter must come before @ after that @must come and gmail or hotmail will com the last .com will come.
        Matcher matcher7 = ptrn7.matcher(text7);
        boolean matchfound7 = matcher7.find();
        if (matchfound7) {

        } else {
            JOptionPane.showMessageDialog(rootPane, "PLEASE WRİTE  A  USERNAME!!!");
            this.dispose();
            new CUSTOMER_PAGE(username1).setVisible(true);
            
          
            return;
        }
                String password = PASSWORD.getText();
//take password
        String text8 = PASSWORD.getText();
        Pattern ptrn8 = Pattern.compile("^(.)+$", Pattern.CASE_INSENSITIVE);//at least one any caracter must come before @ after that @must come and gmail or hotmail will com the last .com will come.
        Matcher matcher8 = ptrn8.matcher(text8);
        boolean matchfound8 = matcher8.find();
        if (matchfound8) {

        } else {
            JOptionPane.showMessageDialog(rootPane, "PLEASE WRİTE    PASSWORD!!!");
            this.dispose();
            new CUSTOMER_PAGE(username1).setVisible(true);
            
        
            return;
        }
        String name = NAME.getText();

        String text3 = NAME.getText();
        Pattern ptrn3 = Pattern.compile("^[a-zA-Z]{3,}$", Pattern.CASE_INSENSITIVE);//name must be just letters and at least 3 letters

        Matcher matcher1 = ptrn3.matcher(text3);
        boolean matchfound3 = matcher1.find();
        if (matchfound3) {

        } else {
            JOptionPane.showMessageDialog(rootPane, "PLEASE WRİTE CORRECT YOUR NAME!!!");//if this is not correct page will be close and will go sign_up page.
            this.dispose();
                        new CUSTOMER_PAGE(username1).setVisible(true);

            return;

        }
        String surname = SURNAME.getText();

        String text4 = SURNAME.getText();
        Pattern ptrn4 = Pattern.compile("^[a-zA-Z]{3,}$", Pattern.CASE_INSENSITIVE);//surname must be just letters and at least 3 letters

        Matcher matcher4 = ptrn4.matcher(text4);
        boolean matchfound4 = matcher4.find();
        if (matchfound4) {

        } else {
            JOptionPane.showMessageDialog(rootPane, "PLEASE WRİTE CORRECT YOUR SURNAME!!!");
            this.dispose();
                      new CUSTOMER_PAGE(username1).setVisible(true);

            return;

        }
        String mail = MAİL.getText();
        String text = MAİL.getText();
        Pattern ptrn1 = Pattern.compile("^(.){1,}@(hotmail|gmail)\\.com$", Pattern.CASE_INSENSITIVE);//at least one any caracter must come before @ after that @must come and gmail or hotmail will com the last .com will come.
        Matcher matcher = ptrn1.matcher(text);
        boolean matchfound = matcher.find();
        if (matchfound) {

           
        } else {
            JOptionPane.showMessageDialog(rootPane, "PLEASE İNCLUDE @hotmail or gmail .com!!!","WARNİNG",JOptionPane.WARNING_MESSAGE);
           this.dispose();
                        new CUSTOMER_PAGE(username1).setVisible(true);

            return;

        }
        String position = POSİTİON.getText();
        String invoince = İNVOİNCE.getText();
int confirm=JOptionPane.showConfirmDialog(rootPane, "ARE YOU SURE UPDATE ?","UPDATE",JOptionPane.YES_NO_OPTION);
if(confirm==JOptionPane.YES_OPTION){
    MANAGE.UpdateCustomer(name, surname, password, mail, position, invoince, username);
JOptionPane.showMessageDialog(rootPane, "UPDATED!!!", "UPDATE",JOptionPane.INFORMATION_MESSAGE);
}
else if(confirm==JOptionPane.NO_OPTION){
    JOptionPane.showMessageDialog(rootPane, " COULDNT UPDATE!!!", "UPDATE",JOptionPane.INFORMATION_MESSAGE);


}
    }//GEN-LAST:event_UPDATEActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        // TODO add your handling code here:
        String username = USERNAME.getText();//we are deleting 
int confirm=JOptionPane.showConfirmDialog(rootPane, "ARE YOU SURE DELETE ?","DELETE",JOptionPane.YES_NO_OPTION);
if(confirm==JOptionPane.YES_OPTION){
     boolean happen= MANAGE.DeleteByUsername(username);
if(happen){
    JOptionPane.showMessageDialog(rootPane,"DELETED!!!","DELETE",JOptionPane.INFORMATION_MESSAGE);
           new LOGİN().setVisible(true);
           this.dispose();
           
}
else{
    JOptionPane.showMessageDialog(rootPane, "COULDNT DELETED!!","DELETE",JOptionPane.INFORMATION_MESSAGE);
}
}
else if(confirm==JOptionPane.NO_OPTION){
    JOptionPane.showMessageDialog(rootPane, " COULDNT DELETE!!!", "DELETE",JOptionPane.INFORMATION_MESSAGE);


}
      

    }//GEN-LAST:event_DELETEActionPerformed

    private void UPDATE_COMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATE_COMActionPerformed
        // TODO add your handling code here:
        String username = USERNAME.getText();//we are updating customer infos

        String com_name = COMPANY_NAME.getText();
        String text5 = COMPANY_NAME.getText();
        Pattern ptrn5 = Pattern.compile("^[a-zA-Z]{3,}(.{0,})$", Pattern.CASE_INSENSITIVE);//company name must start at least 3 letter after that an char can come 

        Matcher matcher5 = ptrn5.matcher(text5);
        boolean matchfound5 = matcher5.find();
        if (matchfound5) {

        } else {
            JOptionPane.showMessageDialog(rootPane, "PLEASE START WİTH AT LEAST THREE CHAR FOR YOUR COMPANY NAME!!!");
            this.dispose();
            new CUSTOMER_PAGE(username).setVisible(true);
            return;

        }
        int confirm=JOptionPane.showConfirmDialog(rootPane, "ARE YOU SURE DELETE ?","DELETE",JOptionPane.YES_NO_OPTION);
if(confirm==JOptionPane.YES_OPTION){
               boolean happen= MANAGE.UpdateCompany(com_name, username);

if(happen){

    JOptionPane.showMessageDialog(rootPane,"UPDATED!!!","UPDATE COMPANY",JOptionPane.INFORMATION_MESSAGE);
           
         
           
}
else{
    JOptionPane.showMessageDialog(rootPane, "COULDNT UPDATED!!","UPDATE COMPANY",JOptionPane.INFORMATION_MESSAGE);
}
}
else if(confirm==JOptionPane.NO_OPTION){
    JOptionPane.showMessageDialog(rootPane, "COULDNT UPDATED!!","UPDATE COMPANY",JOptionPane.INFORMATION_MESSAGE);


}


    }//GEN-LAST:event_UPDATE_COMActionPerformed

    private void enter_revenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_revenueActionPerformed
        // TODO add your handling code here:
        String username = USERNAME.getText();
        String revenue = new_revenue.getText();
        String text1 = new_revenue.getText();
        Pattern ptrn2 = Pattern.compile("^\\d+(\\.\\d+)?$", Pattern.CASE_INSENSITIVE);//this must start with a number after that . and a number can come just once for double numbers.

        Matcher matcher8 = ptrn2.matcher(text1);
        boolean matchfound1 = matcher8.find();
        if (matchfound1) {

        } else {
            JOptionPane.showMessageDialog(rootPane, "PLEASE WRİTE İNT OR DOUBLE POSİTİVE NUMBER!!!");
           this.dispose();
            new CUSTOMER_PAGE(username).setVisible(true);
            return;

        }
        double revenue_money = Double.parseDouble(revenue);// converting double 
        String total = TOTAL.getText();
        double total_money = Double.parseDouble(total);
        double tot = (total_money) + (revenue_money);
        MANAGE.UpdateRevenueInCompany(username, tot, revenue_money);//updating revenue for company_info table

       
        boolean happen= MANAGE.AddRevenue(username, revenue);// adding revenue table 
        if(happen){
                        JOptionPane.showMessageDialog(rootPane, "NEW REVENUE ADDED!!!");

        }
        else{
                                    JOptionPane.showMessageDialog(rootPane, "NEW REVENUE COULDNT ADDED!!!");

        }
    }//GEN-LAST:event_enter_revenueActionPerformed

    private void SHOWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOWActionPerformed
        // TODO add your handling code here:
        new SHOW_EXPENSE(username1).setVisible(true);//customer can see own expenses
this.dispose();

    }//GEN-LAST:event_SHOWActionPerformed

    private void see_expenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_see_expenseActionPerformed
        // TODO add your handling code here:
        String username = USERNAME.getText();

        MANAGE.GetExpenseList(username, model1);//geting expenses from database to table

    }//GEN-LAST:event_see_expenseActionPerformed

    private void see_revenuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_see_revenuesActionPerformed
        // TODO add your handling code here:
        String username = USERNAME.getText();

        MANAGE.GetRevenueList(username, model2);//geting revenues from database to jlist
    }//GEN-LAST:event_see_revenuesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CUSTOMER_PAGE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField COMPANY_NAME;
    private javax.swing.JLabel DEBT;
    private javax.swing.JButton DELETE;
    private javax.swing.JLabel LAST;
    private javax.swing.JList<String> LİST;
    private javax.swing.JTextField MAİL;
    private javax.swing.JTextField NAME;
    private javax.swing.JTextField PASSWORD;
    private javax.swing.JLabel POSİTİON;
    private javax.swing.JButton SHOW;
    private javax.swing.JTextField SURNAME;
    private javax.swing.JTable TABLE;
    private javax.swing.JLabel TOTAL;
    private javax.swing.JLabel TYPE;
    private javax.swing.JButton UPDATE;
    private javax.swing.JButton UPDATE_COM;
    private javax.swing.JLabel USERNAME;
    private javax.swing.JButton enter_revenue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField new_revenue;
    private javax.swing.JButton see_expense;
    private javax.swing.JButton see_revenues;
    private javax.swing.JLabel İNVOİNCE;
    // End of variables declaration//GEN-END:variables
}
