
import com.mycompany.example.COMPANY;
import java.awt.HeadlessException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author akdag
 */
public class EXPENSES extends javax.swing.JFrame {

    String username;

    double total_money = 0;
    COMPANY şirket;
    String ac_username2;

    /**
     * Creates new form EXPENSES
     */
    public EXPENSES(String username, double total_money, String ac_username1) {//this will record accountant and customer and total money of before enter expenses by accountant
        initComponents();
        this.username = username;
        this.total_money = total_money;
        String paralar = String.valueOf(total_money);
        total_bfr.setText(paralar);
        String accountant = String.valueOf(username);
        ac_username2 = ac_username1;//to go back own accountant page 
        USERNAME.setText(accountant);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        salaries = new javax.swing.JTextField();
        rent = new javax.swing.JTextField();
        marketing = new javax.swing.JTextField();
        taxes = new javax.swing.JTextField();
        service = new javax.swing.JTextField();
        transportation = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        calculate = new javax.swing.JButton();
        resttttttt = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        total_bfr = new javax.swing.JLabel();
        USERNAME = new javax.swing.JLabel();
        rest = new javax.swing.JLabel();
        sum = new javax.swing.JLabel();
        MAİN = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Personel Salaries and Insurance");

        jLabel2.setText("Office Rent and Administrative Expenses");

        jLabel3.setText("Marketing and Advertising Expenses");

        jLabel4.setText("Taxes and Legal Obligations");

        jLabel5.setText("Service Procurement and Consultancy Fees");

        jLabel6.setText("Transportation and Logistics Expenses");

        jLabel7.setText("SUM OF EXPENSES  = ");

        calculate.setText("CALCULATE");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        resttttttt.setText("The Rest Quantity");

        jLabel8.setText("TOTAL MONEY BEFORE EX");

        jLabel9.setText("CUSTOMER USERNAME");

        total_bfr.setText("jLabel10");

        USERNAME.setText("jLabel10");

        rest.setText("jLabel10");

        sum.setText("jLabel10");

        MAİN.setText("GO MAIN PAGE");
        MAİN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAİNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(salaries)
                    .addComponent(rent)
                    .addComponent(marketing)
                    .addComponent(taxes)
                    .addComponent(service)
                    .addComponent(transportation, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                    .addComponent(sum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(MAİN, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(resttttttt, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rest, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(USERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(92, 92, 92)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(total_bfr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(salaries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addComponent(total_bfr, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(marketing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(USERNAME)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(resttttttt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rest)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MAİN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(taxes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(service, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(transportation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(sum))
                        .addGap(16, 16, 16))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        String Salaries = salaries.getText();
        String text1 = salaries.getText();// getting accountant inputs and checking all of them must number
        Pattern ptrn1 = Pattern.compile("^\\d+(\\.\\d+)?$", Pattern.CASE_INSENSITIVE);//this must start with a number after that . and a number can come just once for double numbers.

        Matcher matcher1 = ptrn1.matcher(text1);
        boolean matchfound1 = matcher1.find();
        if (matchfound1) {

        } else {
            JOptionPane.showMessageDialog(rootPane, "PLEASE WRİTE İNETEGER OR DOUBLE  POSİTİVE NUMBER!!!");
            new ACCOUNTANT_PAGE(ac_username2).setVisible(true);
            this.dispose();
            return;

        }
        String Rent = rent.getText();
        String text2 = rent.getText();
        Pattern ptrn2 = Pattern.compile("^\\d+(\\.\\d+)?$", Pattern.CASE_INSENSITIVE);//this must start with a number after that . and a number can come just once for double numbers.

        Matcher matcher2 = ptrn2.matcher(text2);
        boolean matchfound2 = matcher2.find();
        if (matchfound2) {

        } else {
            JOptionPane.showMessageDialog(rootPane, "PLEASE WRİTE İNETEGER OR DOUBLE  POSİTİVE NUMBER!!!");
            new ACCOUNTANT_PAGE(ac_username2).setVisible(true);
                       this.dispose();

            return;

        }
        String Marketing = marketing.getText();
        String text3 = marketing.getText();
        Pattern ptrn3 = Pattern.compile("^\\d+(\\.\\d+)?$", Pattern.CASE_INSENSITIVE);//this must start with a number after that . and a number can come just once for double numbers.

        Matcher matcher3 = ptrn3.matcher(text3);
        boolean matchfound3 = matcher3.find();
        if (matchfound3) {

        } else {
            JOptionPane.showMessageDialog(rootPane, "PLEASE WRİTE İNTEGER OR DOUBLE  POSİTİVE NUMBER!!!");
            new ACCOUNTANT_PAGE(ac_username2).setVisible(true);
                        this.dispose();

            return;

        }
        String Taxes = taxes.getText();
        String text4 = salaries.getText();
        Pattern ptrn4 = Pattern.compile("^\\d+(\\.\\d+)?$", Pattern.CASE_INSENSITIVE);//this must start with a number after that . and a number can come just once for double numbers.

        Matcher matcher4 = ptrn4.matcher(text4);
        boolean matchfound4 = matcher4.find();
        if (matchfound4) {

        } else {
            JOptionPane.showMessageDialog(rootPane, "PLEASE WRİTE İNETEGER OR DOUBLE  POSİTİVE NUMBER!!!");
            new ACCOUNTANT_PAGE(ac_username2).setVisible(true);
                        this.dispose();

            return;

        }
        String Services = service.getText();
        String text5 = service.getText();
        Pattern ptrn5 = Pattern.compile("^\\d+(\\.\\d+)?$", Pattern.CASE_INSENSITIVE);//this must start with a number after that . and a number can come just once for double numbers.

        Matcher matcher5 = ptrn5.matcher(text5);
        boolean matchfound5 = matcher5.find();
        if (matchfound5) {

        } else {
            JOptionPane.showMessageDialog(rootPane, "PLEASE WRİTE İNETEGER OR DOUBLE  POSİTİVE NUMBER!!!");
            new ACCOUNTANT_PAGE(ac_username2).setVisible(true);
                        this.dispose();

            return;

        }
        String Transportation = transportation.getText();
        String text6 = transportation.getText();
        Pattern ptrn6 = Pattern.compile("^\\d+(\\.\\d+)?$", Pattern.CASE_INSENSITIVE);//this must start with a number after that . and a number can come just once for double numbers.

        Matcher matcher6 = ptrn6.matcher(text6);
        boolean matchfound6 = matcher6.find();
        if (matchfound6) {

        } else {
            JOptionPane.showMessageDialog(rootPane, "PLEASE WRİTE İNETEGER OR DOUBLE  POSİTİVE NUMBER!!!");
            new ACCOUNTANT_PAGE(ac_username2).setVisible(true);
                        this.dispose();

            return;

        }
        double SALARİES = Double.parseDouble(Salaries);//converting double from string
        double RENT = Double.parseDouble(Rent);
        double MARKETİNG = Double.parseDouble(Marketing);
        double TAXES = Double.parseDouble(Taxes);
        double SERVİCES = Double.parseDouble(Services);
        double TRANSPORTATİON = Double.parseDouble(Transportation);

       

        double total_debt = (SALARİES) + (RENT) + (MARKETİNG) + (TAXES) + (SERVİCES) + (TRANSPORTATİON);

        if (total_money < total_debt) {
            JOptionPane.showMessageDialog(rootPane, "THERE İS NO ENOUGH MONEY!!!");
            new ACCOUNTANT_PAGE(ac_username2).setVisible(true);
            this.dispose();
        } else {
 int confirm=JOptionPane.showConfirmDialog(rootPane, "ARE YOU SURE ENTER EXPENSE ?","EXPENSE",JOptionPane.YES_NO_OPTION);
if(confirm==JOptionPane.YES_OPTION){
               
       boolean debt_list = MANAGE.AddExpense(username, SALARİES, RENT, MARKETİNG, TAXES, SERVİCES, TRANSPORTATİON, total_debt);//ADDİNG EXPENSES TO EXPENSE LİST 
              

if(debt_list){

    JOptionPane.showMessageDialog(rootPane,"Added debts to list!!!","EXPENSE",JOptionPane.INFORMATION_MESSAGE);
           
         
           
}
else{
    JOptionPane.showMessageDialog(rootPane, " COULDNT Add debts to list!!!","EXPENSE",JOptionPane.INFORMATION_MESSAGE);
}
}
else if(confirm==JOptionPane.NO_OPTION){
    JOptionPane.showMessageDialog(rootPane, "COULDNT Add debts to list!!!","EXPENSE",JOptionPane.INFORMATION_MESSAGE);


}

            
               
            

            double rest_money = (total_money - total_debt);//calculate rest money
            String debt = String.valueOf(total_debt);
            sum.setText(debt);

            String rest_total = String.valueOf(rest_money);
            rest.setText(rest_total);
            String REST = rest.getText();
            double REST_MONEY = Double.parseDouble(REST);

            
                boolean happen = MANAGE.UpdateMoneyInCompany(username, REST_MONEY, total_debt);
                if (happen) {
                    JOptionPane.showMessageDialog(rootPane, "Added Expenses!");
                     new ACCOUNTANT_PAGE(ac_username2).setVisible(true);
        this.dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Couldnt be added Expenses!!!");

                }
           
        }
    }//GEN-LAST:event_calculateActionPerformed

    private void MAİNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAİNActionPerformed
        // TODO add your handling code here:
        new ACCOUNTANT_PAGE(ac_username2).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MAİNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EXPENSES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EXPENSES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EXPENSES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EXPENSES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MAİN;
    private javax.swing.JLabel USERNAME;
    private javax.swing.JButton calculate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField marketing;
    private javax.swing.JTextField rent;
    private javax.swing.JLabel rest;
    private javax.swing.JLabel resttttttt;
    private javax.swing.JTextField salaries;
    private javax.swing.JTextField service;
    private javax.swing.JLabel sum;
    private javax.swing.JTextField taxes;
    private javax.swing.JLabel total_bfr;
    private javax.swing.JTextField transportation;
    // End of variables declaration//GEN-END:variables
}
