
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author akdag
 */
public class SEE_ACCOUNTANT extends javax.swing.JFrame {
String ac_username3;
ACCOUNTANT accountant;
    /**
     * Creates new form SEE_ACCOUNTANT
     */
    public SEE_ACCOUNTANT(String ac_username1) {
        initComponents();//will set all accountant infos from accountant class
        ac_username3=ac_username1;
        accountant=MANAGE.GetAccountant(ac_username1);
      USERNAME.setText(accountant.username);
         PASSWORD.setText(accountant.password);
      NAME.setText(accountant.name);
      SURNAME.setText(accountant.surname);
      MAİL.setText(accountant.mail);
      POSİTİON.setText(accountant.position);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        USERNAME = new javax.swing.JLabel();
        POSİTİON = new javax.swing.JLabel();
        NAME = new javax.swing.JTextField();
        PASSWORD = new javax.swing.JTextField();
        SURNAME = new javax.swing.JTextField();
        MAİL = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        UPDATE = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        MAİN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("USERNAME");

        jLabel3.setText("NAME");

        jLabel4.setText("SURNAME");

        jLabel5.setText("MAİL");

        jLabel6.setText("POSİTİON");

        USERNAME.setText("jLabel7");

        POSİTİON.setText("jLabel8");

        NAME.setText("jTextField1");

        PASSWORD.setText("jTextField2");

        SURNAME.setText("jTextField3");

        MAİL.setText("jTextField4");

        jLabel9.setText("PASSWORD");

        UPDATE.setText("UPDATE");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });

        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });

        MAİN.setText("GO MAİN PAGE");
        MAİN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAİNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addGap(133, 133, 133)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(USERNAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(POSİTİON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NAME, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(PASSWORD)
                    .addComponent(SURNAME)
                    .addComponent(MAİL))
                .addGap(129, 129, 129)
                .addComponent(MAİN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(USERNAME))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(SURNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(MAİL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(MAİN)
                        .addGap(41, 41, 41)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(POSİTİON))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UPDATE)
                    .addComponent(DELETE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MAİNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAİNActionPerformed
        // TODO add your handling code here:
        new ACCOUNTANT_PAGE(ac_username3).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MAİNActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
        // TODO add your handling code here:
       String usernamee= USERNAME.getText();
              String passwordd= PASSWORD.getText();//update acco infos with checking
              
       String text9=PASSWORD.getText();
        Pattern ptrn9=Pattern.compile("^(.)+$",Pattern.CASE_INSENSITIVE);

        Matcher matcher9 = ptrn9.matcher(text9);
        boolean matchfound9 = matcher9.find();
        if(matchfound9){
            
        
    }                                        
 else{
                            JOptionPane.showMessageDialog(rootPane,"PLEASE WRİTE  YOUR PASSWORD!!!");
                            this.dispose();
                            new SEE_ACCOUNTANT(ac_username3).setVisible(true);
return;
        }
       String namee= NAME.getText();
       String text3=NAME.getText();
        Pattern ptrn3=Pattern.compile("^[a-zA-Z]{3,}$",Pattern.CASE_INSENSITIVE);

        Matcher matcher1 = ptrn3.matcher(text3);
        boolean matchfound3 = matcher1.find();
        if(matchfound3){
            
        
    }                                        
 else{
                            JOptionPane.showMessageDialog(rootPane,"PLEASE WRİTE CORRECT YOUR NAME!!!");
                            this.dispose();
                            new SEE_ACCOUNTANT(ac_username3).setVisible(true);
return;

        }
       String surnamee= SURNAME.getText();
       String text=SURNAME.getText();
        Pattern ptrn=Pattern.compile("^[a-zA-Z]{3,}$",Pattern.CASE_INSENSITIVE);

        Matcher matcher = ptrn.matcher(text);
        boolean matchfound = matcher.find();
        if(matchfound){
            
        
        
    }                                        
 else{
                            JOptionPane.showMessageDialog(rootPane,"PLEASE WRİTE CORRECT YOUR SURNAME!!!");
                            this.dispose();
                                                        new SEE_ACCOUNTANT(ac_username3).setVisible(true);

return;

        }
       String maill= MAİL.getText();
      String text4=MAİL.getText();
        Pattern ptrn4=Pattern.compile("^(.){1,}@(hotmail|gmail)\\.com$",Pattern.CASE_INSENSITIVE);
        Matcher matcher4 = ptrn4.matcher(text4);
        boolean matchfound4 = matcher4.find();
        if(matchfound4){
            
        
        
    }                                        
 else{
                            JOptionPane.showMessageDialog(rootPane,"PLEASE İNCLUDE @hotmail or gmail .com!!!");
                                                        new SEE_ACCOUNTANT(ac_username3).setVisible(true);

return;

        }

         PASSWORD.getText();
      NAME.setText(accountant.name);
      SURNAME.setText(accountant.surname);
      MAİL.setText(accountant.mail);
      POSİTİON.setText(accountant.position);
        int confirm=JOptionPane.showConfirmDialog(rootPane, "ARE YOU SURE UPDATE ?","UPDATE",JOptionPane.YES_NO_OPTION);
if(confirm==JOptionPane.YES_OPTION){
                      boolean control= MANAGE.UpdateAccountant(namee, surnamee, passwordd, maill, usernamee);

      

if(control){

    JOptionPane.showMessageDialog(rootPane,"UPDATED!!!","UPDATE ACCOUNTANT",JOptionPane.INFORMATION_MESSAGE);
           
         
           
}
else{
    JOptionPane.showMessageDialog(rootPane, " COULDNT UPDATED!!!","UPDATE ACCOUNTANT",JOptionPane.INFORMATION_MESSAGE);
}
}
else if(confirm==JOptionPane.NO_OPTION){
    JOptionPane.showMessageDialog(rootPane, "COULDNT UPDATED!!!","UPDATE ACCOUNTANT",JOptionPane.INFORMATION_MESSAGE);


}


      
       
    }//GEN-LAST:event_UPDATEActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        // TODO add your handling code here:
               String usernamee= USERNAME.getText();
                int confirm=JOptionPane.showConfirmDialog(rootPane, "ARE YOU SURE DELETE ?","DELETE",JOptionPane.YES_NO_OPTION);
if(confirm==JOptionPane.YES_OPTION){
               boolean control=MANAGE.DeleteByUsername(usernamee);//will delete accountant

      

if(control){

    JOptionPane.showMessageDialog(rootPane," DELETED!!!","DELETE ACCOUNTANT",JOptionPane.INFORMATION_MESSAGE);
           new LOGİN().setVisible(true);
         this.dispose();
           
}
else{
    JOptionPane.showMessageDialog(rootPane, " COULDNT DELETED!!!","DELETE ACCOUNTANT",JOptionPane.INFORMATION_MESSAGE);
}
}
else if(confirm==JOptionPane.NO_OPTION){
    JOptionPane.showMessageDialog(rootPane, "COULDNT DELETED!!!","DELETE ACCOUNTANT",JOptionPane.INFORMATION_MESSAGE);


}
       
        
    }//GEN-LAST:event_DELETEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SEE_ACCOUNTANT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SEE_ACCOUNTANT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SEE_ACCOUNTANT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SEE_ACCOUNTANT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DELETE;
    private javax.swing.JTextField MAİL;
    private javax.swing.JButton MAİN;
    private javax.swing.JTextField NAME;
    private javax.swing.JTextField PASSWORD;
    private javax.swing.JLabel POSİTİON;
    private javax.swing.JTextField SURNAME;
    private javax.swing.JButton UPDATE;
    private javax.swing.JLabel USERNAME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
