
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author akdag
 */
public class SİGN_UP extends javax.swing.JFrame {

    boolean stop = false;// when this will be true the codes wii stop likes return

    /**
     * Creates new form SİGN_UP
     */
    public SİGN_UP() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NAME = new javax.swing.JTextField();
        SURNAME = new javax.swing.JTextField();
        MAİL = new javax.swing.JTextField();
        USERNAME = new javax.swing.JTextField();
        PASSWORD = new javax.swing.JTextField();
        İNVOİNCE = new javax.swing.JCheckBox();
        POSİTİON = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        COMPANY_NAME = new javax.swing.JTextField();
        TYPE = new javax.swing.JComboBox<>();
        TOTAL = new javax.swing.JTextField();
        UP = new javax.swing.JButton();
        GO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NAME");

        jLabel2.setText("SURNAME");

        jLabel3.setText("MAİL");

        jLabel4.setText("USERNAME");

        jLabel5.setText("PASSWORD");

        jLabel7.setText("E-İNVOİNCE");

        jLabel8.setText("POSİTİON");

        İNVOİNCE.setText("E-İNVOİNCE");
        İNVOİNCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                İNVOİNCEActionPerformed(evt);
            }
        });

        POSİTİON.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CUSTOMER", "ACCOUNTANT" }));
        POSİTİON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POSİTİONActionPerformed(evt);
            }
        });

        jLabel9.setText("COMPANY NAME");

        jLabel10.setText("TYPE OF COMPANY");

        jLabel11.setText("TOTAL MONEY");

        TYPE.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Sole Priproetership", "Limited Liability", "Cooperative" }));

        UP.setText("SIGN UP");
        UP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPActionPerformed(evt);
            }
        });

        GO.setText("RETURN TO LOGİN PAGE");
        GO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UP, javax.swing.GroupLayout.PREFERRED_SIZE, 382,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel1Layout.createSequentialGroup()
                                                                        .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(
                                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                        jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(jLabel4,
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        93,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jLabel5,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        93,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jLabel3,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        93,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGap(26, 26, 26)
                                                                        .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(MAİL,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        144,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(PASSWORD,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        144,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(USERNAME,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        144,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(NAME,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        144,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(SURNAME,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        144,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGap(179, 179, 179))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 87,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(29, 29, 29)))
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                121, Short.MAX_VALUE)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(37, 37, 37)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(COMPANY_NAME)
                                                        .addComponent(TYPE, 0, 159, Short.MAX_VALUE)
                                                        .addComponent(TOTAL)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(POSİTİON, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(İNVOİNCE, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(86, 86, 86)
                                                .addComponent(GO)))
                                .addContainerGap(200, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(USERNAME, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel9)
                                                        .addComponent(COMPANY_NAME,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel10)
                                                        .addComponent(jLabel1)
                                                        .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addComponent(TYPE, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(SURNAME, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(TOTAL, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(MAİL, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel8)
                                                        .addComponent(POSİTİON, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(21, 21, 21)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel7)
                                                        .addComponent(İNVOİNCE)))
                                        .addComponent(UP, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(GO, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(7, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UPActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_UPActionPerformed

        // TODO add your handling code here:
        String username2 = USERNAME.getText();// take username
        String text7 = USERNAME.getText();
        Pattern ptrn7 = Pattern.compile("^(.)+$", Pattern.CASE_INSENSITIVE);// at least one any caracter must come
                                                                            // before @ after that @must come and gmail
                                                                            // or hotmail will com the last .com will
                                                                            // come.
        Matcher matcher7 = ptrn7.matcher(text7);
        boolean matchfound7 = matcher7.find();
        if (matchfound7) {

        } else {
            JOptionPane.showMessageDialog(rootPane, "PLEASE WRİTE  A  USERNAME!!!");
            this.dispose();
            new SİGN_UP().setVisible(true);

            stop = true;
            return;
        }
        String password2 = PASSWORD.getText();// take password
        String text8 = PASSWORD.getText();
        Pattern ptrn8 = Pattern.compile("^(.)+$", Pattern.CASE_INSENSITIVE);// at least one any caracter must come
                                                                            // before @ after that @must come and gmail
                                                                            // or hotmail will com the last .com will
                                                                            // come.
        Matcher matcher8 = ptrn8.matcher(text8);
        boolean matchfound8 = matcher8.find();
        if (matchfound8) {

        } else {
            JOptionPane.showMessageDialog(rootPane, "PLEASE WRİTE    PASSWORD!!!");
            this.dispose();
            new SİGN_UP().setVisible(true);

            stop = true;
            return;
        }
        String name2 = NAME.getText();// taking inputs and checking
        String text = NAME.getText();
        Pattern ptrn = Pattern.compile("^[a-zA-Z]{3,}$", Pattern.CASE_INSENSITIVE);// name must be just letters and at
                                                                                   // least 3 letters

        Matcher matcher = ptrn.matcher(text);
        boolean matchfound = matcher.find();
        if (matchfound) {

        } else {
            JOptionPane.showMessageDialog(rootPane, "PLEASE WRİTE CORRECT YOUR NAME!!!");
            this.dispose();// when didnt correct type of input this page will close.
            new SİGN_UP().setVisible(true);
            stop = true;
            return;
        }
        String surname2 = SURNAME.getText();
        String text40 = SURNAME.getText();
        Pattern ptrn40 = Pattern.compile("^[a-zA-Z]{3,}$", Pattern.CASE_INSENSITIVE);// surname must be just letters and
                                                                                     // at least 3 letters

        Matcher matcher40 = ptrn40.matcher(text40);
        boolean matchfound40 = matcher40.find();
        if (matchfound40) {

        } else {
            JOptionPane.showMessageDialog(rootPane, "PLEASE WRİTE CORRECT YOUR SURNAME!!!");
            this.dispose();
            new SİGN_UP().setVisible(true);
            stop = true;
            return;
        }
        String mail2 = MAİL.getText();
        String text2 = MAİL.getText();
        Pattern ptrn2 = Pattern.compile("^(.){1,}@(hotmail|gmail)\\.com$", Pattern.CASE_INSENSITIVE);// at least one any
                                                                                                     // caracter must
                                                                                                     // come before @
                                                                                                     // after that @must
                                                                                                     // come and gmail
                                                                                                     // or hotmail will
                                                                                                     // com the last
                                                                                                     // .com will come.
        Matcher matcher2 = ptrn2.matcher(text2);
        boolean matchfound2 = matcher2.find();
        if (matchfound2) {

        } else {
            JOptionPane.showMessageDialog(rootPane,
                    "PLEASE WRİTE AT LEAST ONE CHAR BEFORE @ THEN İNCLUDE @hotmail or gmail .com!!!");
            this.dispose();
            new SİGN_UP().setVisible(true);

            stop = true;
            return;
        }

        String invoince; // this will equal true or false according to select "invoince" checkbox.
        String position2 = (String) POSİTİON.getSelectedItem();// convert selected position from combobox to string

        if ("ACCOUNTANT".equals(position2)) {

            boolean success = MANAGE.AddACCOUNTANT(username2, password2, name2, surname2, mail2, position2);// if
                                                                                                            // selected
                                                                                                            // is
                                                                                                            // accountant
                                                                                                            // will add
                                                                                                            // to as
                                                                                                            // accountant
                                                                                                            // this
                                                                                                            // user.
            if (stop == false) {// this will run like return if stop doesnt be true
                if (success) {
                    JOptionPane.showMessageDialog(rootPane, "USER ADDED!!!");

                    this.dispose();
                    new LOGİN().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "USER  NOT ADDED!!!");
                    this.dispose();
                    new LOGİN().setVisible(true);
                    stop = true;
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "USER  NOT ADDED!!!");
                this.dispose();
                new LOGİN().setVisible(true);
                return;
            }
        } else if ("CUSTOMER".equals(position2)) {// if user select customer

            if (İNVOİNCE.isSelected()) {
                invoince = "true";
            } else {
                invoince = "false";
            }
            String company_name2 = COMPANY_NAME.getText();

            String text4 = COMPANY_NAME.getText();
            Pattern ptrn4 = Pattern.compile("^[a-zA-Z]{3,}(.)*$", Pattern.CASE_INSENSITIVE);// company name must start
                                                                                            // at least 3 letter after
                                                                                            // that an char can come

            Matcher matcher4 = ptrn4.matcher(text4);
            boolean matchfound4 = matcher4.find();
            if (matchfound4) {

            } else {

                JOptionPane.showMessageDialog(rootPane,
                        "PLEASE START WİTH AT LEAST THREE LETTER FOR YOUR COMPANY NAME!!!");
                this.dispose();
                new SİGN_UP().setVisible(true);
                stop = true;
                return;
            }
            String number = TOTAL.getText();
            String text5 = TOTAL.getText();
            Pattern ptrn5 = Pattern.compile("^\\d+(\\.\\d+)?$", Pattern.CASE_INSENSITIVE);// this must start with a
                                                                                          // number after that . and a
                                                                                          // number can come just once
                                                                                          // for double numbers.

            Matcher matcher5 = ptrn5.matcher(text5);
            boolean matchfound5 = matcher5.find();
            if (matchfound5) {

            } else {
                JOptionPane.showMessageDialog(rootPane, "PLEASE WRİTE İNETEGER OR DOUBLE  POSİTİVE NUMBER!!!");
                this.dispose();
                new SİGN_UP().setVisible(true);
                stop = true;
                return;
            }

            double total_money = Double.parseDouble(number);
            String type2 = (String) TYPE.getSelectedItem();// convert type from combobox to string

            if (stop == false) {

                boolean success4 = MANAGE.AddCUSTOMER(username2, password2, name2, surname2, mail2, position2, invoince,
                        company_name2, type2, total_money);

                if (success4) {
                    JOptionPane.showMessageDialog(rootPane, "USER ADDED!!!");
                    new LOGİN().setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(rootPane, "PLEASE TRY ANOTHER USERNAME !!!");
                    new LOGİN().setVisible(true);
                    this.dispose();

                }
            } else {// if stop is true taht means the input is wrong type
                JOptionPane.showMessageDialog(rootPane, "USER  NOT 2 ADDED!!!");
                this.dispose();
                new LOGİN().setVisible(true);
                return;
            }
        }

    }// GEN-LAST:event_UPActionPerformed

    private void İNVOİNCEActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_İNVOİNCEActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_İNVOİNCEActionPerformed

    private void POSİTİONActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_POSİTİONActionPerformed
        // TODO add your handling code here:
        String selectedPosition = (String) POSİTİON.getSelectedItem();// taking selectedposition from combobox to string

        boolean isCustomer = "CUSTOMER".equals(selectedPosition);// if this customer "iscustomer" will be true

        // if this is true this 4 will open ,if this is not these will close.
        İNVOİNCE.setEnabled(isCustomer);
        COMPANY_NAME.setEnabled(isCustomer);
        TYPE.setEnabled(isCustomer);
        TOTAL.setEnabled(isCustomer);
    }// GEN-LAST:event_POSİTİONActionPerformed

    private void GOActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_GOActionPerformed
        // TODO add your handling code here:
        new LOGİN().setVisible(true);
        this.dispose();
    }// GEN-LAST:event_GOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SİGN_UP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SİGN_UP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SİGN_UP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SİGN_UP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SİGN_UP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField COMPANY_NAME;
    private javax.swing.JButton GO;
    private javax.swing.JTextField MAİL;
    private javax.swing.JTextField NAME;
    private javax.swing.JTextField PASSWORD;
    private javax.swing.JComboBox<String> POSİTİON;
    private javax.swing.JTextField SURNAME;
    private javax.swing.JTextField TOTAL;
    private javax.swing.JComboBox<String> TYPE;
    private javax.swing.JButton UP;
    private javax.swing.JTextField USERNAME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox İNVOİNCE;
    // End of variables declaration//GEN-END:variables
}
